// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRowogsOs7LcatTN2mFl_zBlfuP9bdcPo',
    appId: '1:325183103914:web:41ac6a892f85f6e32dc1d3',
    messagingSenderId: '325183103914',
    projectId: 'collegeproject-evntq',
    authDomain: 'collegeproject-evntq.firebaseapp.com',
    storageBucket: 'collegeproject-evntq.appspot.com',
    measurementId: 'G-0W7MN1V16J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAWclFPEFMHLnqol-L7IQqeSOW-EBwThA',
    appId: '1:325183103914:android:0805912c9eeadd6d2dc1d3',
    messagingSenderId: '325183103914',
    projectId: 'collegeproject-evntq',
    storageBucket: 'collegeproject-evntq.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8X9RDoioe1wbDemvjWPK4sPxL11J1BXA',
    appId: '1:325183103914:ios:cacaf7d9c343a4a52dc1d3',
    messagingSenderId: '325183103914',
    projectId: 'collegeproject-evntq',
    storageBucket: 'collegeproject-evntq.appspot.com',
    iosClientId: '325183103914-udk4hsgssduccv1rsgcloe8f007112s2.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventique',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8X9RDoioe1wbDemvjWPK4sPxL11J1BXA',
    appId: '1:325183103914:ios:cacaf7d9c343a4a52dc1d3',
    messagingSenderId: '325183103914',
    projectId: 'collegeproject-evntq',
    storageBucket: 'collegeproject-evntq.appspot.com',
    iosClientId: '325183103914-udk4hsgssduccv1rsgcloe8f007112s2.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventique',
  );
}
